version: '3'

services:
  app:
    container_name: app
    build: .
    ports:
      - '8080:8080'
    env_file: .env
    depends_on: [mysql]
  mysql:
    image: mysql
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_DATABASE: ${DATABASE_NAME}
    ports:
      - '3309:3306'
    volumes:
      - /var/lib/mysql